        const lafeestufortuna = {
        id: "lafeestufortuna",
        titulo: "La Fe es tu Fortuna",
        autor: "Neville Goddard",

        capitulos: [

            {
                nombre: "PRÓLOGO",
                texto: `“Pedid y se os dará.” - Mateo VII-7
La fe del hombre en Dios se mide por su confianza en sí mismo.
Si una persona quiere beneficiarse de la lectura de este libro, es necesaria la comprensión.
Existen dos grandes corrientes de pensamiento en el mundo. La gran masa de personas del mundo Occidental está moldeada para una forma de pensar extrovertida: una vasta fabricación de conocimientos, que son modificados constantemente mientras el individuo continúa combinando los llamados conocimientos de su prójimo.
Una pequeña minoría consigue separarse de estos pensamientos moldeados y escapar al ámbito del pensamiento en el que su propia consciencia gobierna como una autoridad. Esta minoría desarrolla una actitud espiritual claramente definida hacia la vida.
Este estado de consciencia puede conseguirse, sin duda, a través de la fe, pero el verdadero significado de la fe, y su potencial ilimitado, han desempeñado un papel tan pequeño en esta forma de pensar extrovertida, que se ha convertido en un obstáculo en nuestra época actual de la vida. Es prácticamente desconocida para la gran mayoría.
La mejor manera de conseguir tener una idea clara de lo que es una consciencia gobernada por la fe es familiarizándonos íntimamente con la literatura bíblica del mundo. Esta es la única literatura que ha pasado la prueba del tiempo. Todos los demás escritos se convierten rápidamente en verdades anticuadas. Cada afirmación pronunciada o cada hecho registrado en la gran masa de escritos del mundo es una connotación de la sólida literatura bíblica.
El verdadero mensaje de este libro está formado por repetidas instrucciones directas sobre cómo enfocar la literatura bíblica y cómo interpretarla para llegar a tener una comprensión clara de la fe y de su influencia ilimitada en la consciencia individual.
Un dato por sí solo, que se presenta enérgicamente en las enseñanzas de Neville, habla de su integridad, es decir, que se puede ayudar a la persona con un enfoque comprensible de esta literatura y de sus efectos en la consciencia, pero una vez que se ha conseguido una comprensión suficiente, su interpretación depende enteramente de ella. Para ir más lejos en este punto, el autor señala simplemente que sus propios escritos deberían ser estudiados repetidamente hasta que se consiga un enfoque iluminado de la Biblia.
En este estudio, es posible que las lecturas y los significados decididos estén lejanos en el tiempo, haciendo que sea necesario fijar definitivamente las impresiones iniciales en la consciencia.
Es mediante la acumulación de estos estados de consciencia fijados, decididos con precisión, que el autor desarrolla gradualmente dentro de otro, que la comprensión de la fe se desarrolla de manera paralelamente a la comprensión de uno mismo.
Scott R. Edwards, licenciado en Ciencias,
doctor en medicina, miembro del Colegio
Norteamericano de Cirujanos.`
            },
            {
                nombre: "ANTES DE ABRAHAM",
                texto: `En verdad os digo que antes de que existiera Abraham, YO SOY.JUAN 8,58
“En el principio era la Palabra, y la Palabra estaba con Dios, y la Palabra era Dios.”
En el principio existía la consciencia no condicionada de ser, y la consciencia no condicionada de ser se tornó condicionada al imaginarse que era algo, y la consciencia no condicionada de ser se convirtió en aquello que había imaginado ser. Así comenzó la creación.
Por esta ley (primero concebir, luego convertirse en lo concebido), todas las cosas evolucionan a partir de la Nada, y sin esta secuencia no hay nada que sea creado.
Antes de que existiera Abraham, o el mundo, YO SOY. Cuando todo el tiempo deje de existir, YO SOY. YO SOY la consciencia informe de ser, concibiéndome como una persona. Por mi eterna ley del ser, debo ser y expresar todo lo que creo ser.
Yo SOY la eterna Nada que contiene dentro de mi ser informe la capacidad de ser todas las cosas. Yo SOY aquello en lo que viven, se mueven y tienen su existencia todas mis ideas de mí mismo, y no existen separadas de eso.
Habito dentro de cada concepto de mí mismo y, desde esa interioridad, busco continuamente trascender todos los conceptos de mí mismo, únicamente porque creo ser eso que trasciende.
Yo SOY la ley del ser y, aparte de MÍ, no hay ninguna ley. Yo SOY lo que Yo SOY.
`
            },
                      {
                nombre: "TÚ DECRETARÁS",
                texto: `Así, la palabra que salga de mi boca no regresará  a mí vacía, sino que realizará lo que yo deseo, y llevará a cabo aquello que la envié a hacer. ISAÍAS 55,11
El hombre puede decretar una cosa y entonces ocurrirá.
El ser humano siempre ha decretado aquello que ha aparecido en su mundo. Actualmente está decretando lo que está apareciendo en su mundo y continuará haciéndolo mientras siga siendo consciente de que es un ser humano.
Jamás ha aparecido nada en el mundo que el hombre no haya decretado que aparezca. Puedes negar esto, pero por mucho que lo intentes no puedes refutarlo, porque este acto de decretar se basa en un principio inmutable. El ser humano no ordena que las cosas aparezcan mediante sus palabras, las cuales, en la mayoría de los casos, son una confesión de sus dudas y sus temores. Decretar es algo que se hace en la consciencia.
Toda persona expresa automáticamente aquello que es consciente de ser. Sin ningún esfuerzo, o sin utilizar palabras, en cada momento, la persona está ordenándose a sí misma ser y poseer aquello que es consciente de ser y de poseer. Este principio inmutable de expresión está escenificado en todas las Biblias del mundo. Los escritores de nuestros libros sagrados eran místicos iluminados, maestros del pasado en el arte de la psicología. Al contar la historia del alma, personificaron este principio impersonal en la forma de un documento histórico, tanto pata preservarlo como para ocultarlo de los ojos de los no iniciados.
Actualmente, aquellas personas a las que les ha sido confiado este gran tesoro, es decir, el clero del mundo, han olvidado que las Biblias son dramas psicológicos que representan la consciencia del hombre; en su ciego olvido, ahora enseñan a sus seguidores a adorar a sus personajes como si fueran hombres y mujeres que realmente vivieron en el tiempo y el espacio.
Cuando el ser humano vea la Biblia como un gran drama psicológico en el que todos sus personajes y actores son la personificación de las cualidades y los atributos de su propia consciencia, entonces, y sólo entonces, la Biblia le revelará la luz de su simbología. Este principio impersonal de la vida que creó todas las cosas está representado como Dios. Descubrimos que este Señor Dios, creador del Cielo y de la Tierra, es la consciencia de ser del hombre. Si las personas estuvieran menos limitadas por la ortodoxia y observaran de una forma más intuitiva, no podrían evitar notar, al leer la Biblia, que la consciencia de ser es revelada cientos de veces a lo largo de ese texto. Por nombrar unas pocas: "EL YO SOY me ha enviado a vosotros". "Quédate tranquilo y sabe que Yo SOY Dios." "Yo SOY el Señor y no hay ningún Dios." "Yo SOY el pastor." "Yo SOY la puerta." "Yo SOY la resurrección y la vida." "Yo SOY el camino." "Yo SOY el principio y el fin."
Yo SOY; la consciencia de ser no condicionada del ser humano es revelada como el Señor y el creador de todos los estados condicionados de ya existencia. Si el hombre pudiera abandonar su creencia en un Dios separado de él, reconociendo que su consciencia de ser es Dios (consciencia que se forma a imagen y semejanza de su idea de sí mismo), transformaría su mundo, que dejaría de ser un desierto estéril para convertirse en un terreno fértil de su agrado.
El día en que el ser humano haga esto sabrá que él y su Padre son uno, pero su Padre es más grande que él. Sabrá que su consciencia de ser es una con aquello que él es consciente de ser, pero que su consciencia no condicionada de ser es más grande que su estado condicionado o su idea de sí mismo.
Cuando el ser humano descubra que su consciencia es el poder de expresión impersonal, un poder que se representa eternamente en sus ideas de sí mismo, adoptará y se apropiará de ese estado de consciencia que desea expresar. Al hacer esto, se convertirá en ese estado de expresión.
"Decretarás una cosa y entonces ocurrirá" puede expresarse ahora de la siguiente manera: Serás consciente de ser o poseer una cosa y entonces expresarás o poseerás aquello que eres consciente de ser.
La ley de la consciencia es la única ley de expresión. "Yo SOY el camino." "Yo SOY la resurrección". La consciencia es el camino, así como el poder que resucita y expresa todo lo que el ser humano es consciente de ser.
Apártate de la ceguera de la persona no iniciada que intenta expresar y poseer esas cualidades y cosas que no es consciente de ser y poseer, y sé el místico iluminado que decreta en la base de esta ley inmutable. Declara conscientemente que eres eso que deseas; aprópiate de la consciencia de eso que deseas, y tú también conocerás la posición del verdadero místico, de la siguiente manera:
Yo he llegado a ser consciente de ser eso. Todavía soy consciente de ser eso. Y seguiré siendo consciente de ser eso, hasta que aquello que soy consciente de ser se exprese a la perfección.
Sí, decretaré una cosa y entonces ocurrirá.`
            },
                      {
                nombre: "EL PRINCIPIO DE LA VERDAD",
                texto: `Conoceréis la verdad y la verdad os hará libres. JUAN 8,32
"Conoceréis la verdad y la verdad os hará libres".
La verdad que libera al hombre es el conocimiento de que su consciencia es la resurrección y la vida, de que su consciencia resucita y da vida a todo lo que él es consciente de ser. Fuera de la consciencia, no existen ni la resurrección ni la vida.
Cuando el ser humano renuncie a su creencia en un Dios separado de él y empiece a reconocer que su consciencia de ser es Dios, como hicieron Jesús y los profetas, entonces transformará su mundo al darse cuenta de que "Mi Padre y yo somos uno, pero mi Padre es más grande que yo". Sabrá que su consciencia es Dios y que aquello que él es consciente de ser es el hijo que es testigo de Dios, el Padre.
El que concibe una idea y la idea concebida son uno, pero el que concibe es más grande que aquello que concibe. Antes de que existiera Abraham, Yo SOY. SÍ, yo era consciente de existir antes de ser consciente de que soy una persona, y el día en que deje de ser consciente de que soy una persona, seguiré siendo consciente de que existo.
La consciencia de ser no depende de que uno sea nada. Precedió a todas las ideas de sí misma y seguirá existiendo cuando todas las ideas de sí misma dejen de existir. "Yo SOY el principio y el fin." Es decir, todas las cosas o las ideas de mí mismo empiezan y acaban en mí, pero yo, la consciencia informe, permaneceré eternamente.
Jesús descubrió esta gloriosa verdad y declaró que Él era uno con Dios, no con el Dios que el hombre había creado, porque El jamás reconoció a ese Dios. Jesús descubrió que Dios era Su consciencia de ser y por eso le dijo al hombre que el Reino de Dios y el Cielo estaban en el interior.
Cuando se dice que Jesús abandonó el mundo y se marchó con Su Padre, simplemente se está afirmando que El alejó su atención del mundo de los sentidos y elevó su consciencia hasta ese nivel que deseaba expresar. Ahí permaneció hasta que se volvió uno con la consciencia a la que El ascendió. Cuando regresó al mundo humano, pudo actuar con la seguridad positiva de que El era consciente de ser, un estado de consciencia que sólo El sentía o sabía que poseía. La persona que ignora esta ley eterna de expresión ve esos acontecimientos como milagros.
Elevar tu consciencia hasta el nivel de la cosa deseada y permanecer ahí hasta que ese nivel se convierta en tu naturaleza es el camino que lleva a lo que aparentemente son milagros. "Y yo, si soy elevado, a todos los atraeré hacia mí." Si soy elevado en consciencia hasta la naturalidad de la cosa deseada, atraeré la manifestación de ese deseo hacia mí.
"Ninguna persona viene a mí si no es atraída por el Padre que está dentro de mí, y mi Padre y yo somos uno." Mi consciencia es el Padre que atrae la manifestación de la vida hacia mí. La naturaleza de la manifestación está determinada por el estado de consciencia en el que habito. Siempre estoy atrayendo a mi mundo aquello que soy consciente de ser.
Si estás insatisfecho con tu actual expresión de vida, entonces debes volver a nacer. El renacimiento es abandonar ese nivel con el que estás insatisfecho y elevarte al nivel de consciencia que deseas expresar y poseer.
No puedes servir al mismo tiempo a dos señores o estados de consciencia opuestos. Al retirar tu atención de un estado y colocarla en el otro, mueres para el que has dejado y vives y expresas aquel al que estás unido.
El ser humano no entiende cómo es posible que pueda expresar aquello que desea ser por una ley tan simple como la de adquirir la consciencia de lo deseado. El motivo de esta falta de fe por parte del hombre es que ve el estado deseado a través de la consciencia de sus limitaciones actuales. Por lo tanto, naturalmente, la ve como algo imposible de conseguir. 
Una de las primeras cosas que el ser humano debe saber es que,  al tratar con esta ley espiritual de la consciencia, no se puede poner vino nuevo en botellas viejas, o nuevos parches en ropa vieja. Es decir, que uno no puede llevar al nuevo estado de consciencia nada del actual estado de consciencia. Porque el estado buscado es que, está completo en sí mismo y no necesita parches. Cada nivel de consciencia se expresa automáticamente.
Elevarte hasta el nivel de cualquier estado es convertirte automáticamente en ese estado en expresión. Pero para poder elevarte al nivel que actualmente no estás expresando, debes dejar aparte la consciencia con la que ahora te identificas. Hasta que no hayas dejado tu consciencia actual, no podrás elevarte a otro nivel. No te desanimes. Abandonar tu identidad actual no es tan difícil como podría parecer. La invitación de las escrituras: "Estar ausente del cuerpo y estar presente con el Señor" no es para unos pocos elegidos; es un llamamiento general a toda la humanidad. El cuerpo del que se te está invitando a escapar es tu idea actual de ti mismo, con todas sus limitaciones, mientras que el Señor con el que debes estar presente es tu consciencia de ser.
Para realizar esta proeza aparentemente imposible, debes apartar tu atención de tu problema y colocarla en el simple hecho de existir. Dices en silencio, pero con sentimiento: "Yo SOY". No condiciones esta consciencia y sigue declarando: "Yo SOY — Yo SOY". Simplemente, siente que no tienes rostro ni forma, y continúa haciéndolo hasta que sientas que flotas.
"Flotar" es un estado psicológico que niega completamente lo físico. Mediante la práctica, en estado de relajación y negándote de buena gana a reaccionar a las impresiones sensoriales, es posible desarrollar un estado de consciencia de receptividad pura. Esto es algo sorprendentemente fácil de lograr. En este estado de desapego absoluto, una clara firmeza de pensamiento intencionado puede ser grabada indeleblemente en tu consciencia no modificada. Este estado de consciencia es necesario para una auténtica meditación.
Esta maravillosa experiencia de elevarte y flotar es la señal de que estás ausente del cuerpo o del problema y que ahora estás presente en el Señor. En este estado expandido sólo eres consciente de ser el YO SOY – YO SOY; sólo eres consciente de existir. 
Cuando se logra esta expansión de la consciencia, dentro de esta profundidad informe de ti mismo, debes dar forma a la nueva idea declarando y sintiendo que eres aquello que deseabas ser antes de entrar en este estado. Descubrirás que dentro de esa profundidad informe de ti mismo todas las cosas parecen ser divinamente posibles. Cualquier cosa que sinceramente sientas que eres mientras estás en este estado expandido se convierte, con el tiempo, en tu expresión natural.
Y Dios dijo: "Haya un firmamento entre las aguas". Sí, que haya una firmeza o convicción en medio de esta consciencia expandida, mediante el saber y el sentir que YO SOY eso, la cosa deseada.
Cuando declaras y sientes que eres la cosa deseada, estás cristalizando esa luz líquida informe que tú eres, coinvirtiéndola en la imagen y semejanza de aquello que eres consciente de ser.
Ahora que la ley de tu ser te ha sido revelada, comienza hoy mismo a cambiar tu mundo mediante la reevaluación de ti mismo. Durante demasiado tiempo, el hombre se ha aferrado a la creencia de que nace del dolor y de que debe conseguir su salvación con el sudor de su frente. Dios es impersonal y no hace diferencias entre las personas. Mientras el ser humano continúe teniendo esta creencia de dolor, seguirá caminando en un mundo de tristeza y confusión, porque el mundo, en todos sus detalles, es la consciencia del ser humano cristalizada.
En el Libro de los Números está escrito: "Había gigantes en las tierras y a nosotros nos pareció que éramos como saltamontes, y a ellos les pareció que nosotros éramos como saltamontes".
Hoy es el día, el ahora eterno, en el que las condiciones en el mundo han alcanzado la apariencia de gigantes. Los desempleados, los ejércitos del enemigo, la competitividad en los negocios, etc., son los gigantes que hacen que te sientas como un saltamontes indefenso.
Nos dicen que primero nos pareció que éramos como saltamontes y que, debido a este concepto de nosotros mismos, fuimos para el enemigo como saltamontes.
Para los demás sólo podemos ser aquello que pensamos de nosotros mismos. Por lo tanto, si nos reevaluamos y empezamos a sentir que somos el gigante, un centro de poder, automáticamente cambiamos nuestra relación con los gigantes, reduciendo a esos monstruos a su verdadero lugar, haciendo que parezca que son ellos los saltamontes indefensos.
Pablo dijo al respecto: "Para los Griegos (los llamados sabios del mundo) es necedad; y para los judíos (o aquellos que buscan señales), un obstáculo", con el resultado de que el hombre continúa caminando en la oscuridad, en lugar de despertar a la consciencia de que "YO SOY la luz del mundo".
El ser humano ha adorado durante tanto tiempo las imágenes que él mismo ha fabricado, que al principio le parece que esta revelación es blasfema, pero el día que descubra y acepte este principio como la base de su vida, ese día aca-bará con su creencia en un Dios que está separado de él.
La historia de la traición a Jesús en el jardín de Getsemaní ilustra a la perfección el descubrimiento de este principio por parte del hombre. En ella se nos cuenta que la muchedumbre, armada con palos y antorchas, buscaba a Jesús en la oscuridad de la noche. Mientras preguntaban dónde estaba Jesús (la salvación), la voz respondió: "YO SOY", ante lo cual la multitud cayó al suelo. Al recuperar la compostura, volvieron a pedir que se les mostrara el escondite del salvador y, una vez más, el salvador dijo: "Os he dicho que YO SOY. Por lo tanto, si me buscáis, dejad todo lo demás".
El hombre, en la oscuridad de la ignorancia humana, sale a buscar a Dios, ayudado por la luz parpadeante de la sabiduría humana. Cuando se le revela que su YO SOY, o consciencia de ser, es su salvador, la conmoción es tan grande que, mentalmente, cae al suelo, porque todas sus creencias se tambalean al comprender que su consciencia es su único salvador. El conocimiento de que su Yo SOY es Dios obliga a la persona a dejar a todas las demás, porque le resulta imposible servir a dos dioses. El ser humano no puede aceptar que su consciencia de ser es Dios y, al mismo tiempo, creer en otra deidad.
Con este descubrimiento, la oreja o la audición del hombre (la comprensión) es cortada por la espada de la fe (Pedro) mientras que su oído perfecto y disciplinado (la comprensión) es restablecido por (Jesús) el conocimiento de que el YO SOY es el Señor y el Salvador.
Para que la persona pueda transformar su mundo, primero debe echar estos cimientos, o tener esta comprensión. YO SOY el Señor. La persona debe saber que su consciencia de ser es Dios. Hasta que esto esté firmemente establecido, de manera que ninguna sugerencia o argumento de los demás pueda hacerle flaquear, se encontrará regresando a la esclavitud de su antigua forma de ser. "Si no crees que Yo SOY Él, morirás en tus pecados." A menos que la persona descubra que su consciencia es la causa de todas las expresiones de su vida, continuará buscando la causa de su confusión en el mundo de los efectos, y entonces morirá en su infructífera búsqueda.
"Yo SOY la vid y vosotros sois las ramas." La consciencia es la vida, y aquello que eres consciente de ser es como las ramas a las que alimentas y mantienes vivas. Del mismo modo que la rama no tiene vida si no está adherida a la vid, las cosas no tienen vida si tú no eres consciente de ellas. Así como una rama se marchita y muere si la savia de la vid deja de fluir hacia ella, también las cosas y las cualidades desaparecen si retiras tu atención de ellas; porque tu atención es la savia de vida que sustenta la expresión de tu vida.`
            },
                                {
                nombre: "¿A QUIÉN BUSCAS?",
                texto: `Os he dicho que Yo SOY; por lo tanto, si me buscáis a mí, dejad que éstos se vayan. retrocedieron y cayeron en la tierra. JUAN 18,6
Hoy en día se dicen tantas cosas sobre los Maestros, los Hermanos Mayores, los Expertos y los iniciados, que numerosos buscadores de la verdad están siendo llevados continuamente a conclusiones erróneas al buscar estas falsas luces Por un precio, la mayoría de estos seudo-maestros ofrece a sus alumnos una iniciación a los misterios, prometiéndoles orientación y dirección. La debilidad del ser humano por los líderes, así como su culto a los ídolos, lo convierte en presa fácil para estas escuelas y estos maestros. La mayoría de estos estudiantes tiene buena voluntad y, después de años de espera y sacrificios, acaba descubriendo que estaba siguiendo un espejismo. Sienten que sus escuelas y sus metros los han decepcionado, y esta desilusión valdrá el esfuerzo y el pre¬cio que han pagado por su búsqueda infructuosa. Entonces dejarán de adorar al hombre y, al hacerlo, descubrirán que aquello que buscan no se encuentra en otra persona, porque el Reino del Cielo está en su interior. Darse cuenta de esto será su primera iniciación verdadera. La lección aprendida será ésta: Sólo hay un Maestro y ese Maestro es Dios, el Yo SOY, que está dentro de nosotros mismos.
“Yo SOY el Señor tu Dios, que te conducirá fuera de la tierra de la oscuridad; fuera de la casa de la esclavitud.” El Yo SOY, tu consciencia, es el Señor y el Maestro y, aparte de tu consciencia, no hay ningún Señor ni ningún Maestro. Tú eres el Señor de todo aquello de lo que eres consciente de ser.
Sabes que lo eres, ¿no es verdad? Saber que eres algo es el Señor y el Maestro de aquello que sabes que eres. Podrían aislarte completamente de aquello que eres consciente de ser; sin embargo, a pesar de todas las barreras humanas, podrías atraer hacia ti, sin esfuerzo, todo lo que eres consciente de ser. La persona que es consciente de ser pobre no necesita la ayuda de nadie para expresar su pobreza. La persona que es consciente de estar enferma, aunque sea aislada en la zona más herméticamente sellada y libre de gérmenes del mundo, expresaría su enfermedad.
No hay ninguna barrera para Dios, porque Dios es tu consciencia de ser. Independientemente de lo que seas consciente de ser, puedes expresarlo sin esfuerzo, y lo haces. Deja de esperar a que llegue un Maestro; él está contigo siempre. “Yo ESTOY contigo siempre, incluso hasta el fin del mundo.”
De vez en cuando sabrás que eres muchas cosas, pero no necesitas ser nada para saber que lo eres. Si lo deseas, puedes desprenderte del cuerpo que tienes; al hacerlo, te darás cuenta de que eres una consciencia sin rostro, sin forma, y que no dependes de tu forma para expresarte. Sabrás que eres y, además, descubrirás que el hecho de saber que eres es Dios, el Padre, que precedió a todo aquello que alguna vez has sabido que eres. Antes de que existiera el mundo, tú eras consciente de existir y, por lo tanto, decías: “Yo SOY”. Y el Yo SOY existirá después de que todo aquello que sabes que eres deje de ser.
No existen los Maestros Ascendidos. Acaba con esa superstición. Siempre estarás elevándote de un nivel de consciencia (maestro) a otro, y al hacerlo manifestarás el nivel ascendido, expresando esa consciencia recientemente adquirida.
Dado que la consciencia es el Maestro y el Señor, tú eres el Mago Maestro que hace que se manifieste aquello que ahora eres consciente de ser. “Porque Dios (la consciencia) llama a aquellas cosas que no existen como si existieran.” Las cosas que ahora no existen serán vistas en cuanto seas consciente de ser aquello que ahora no ves.
El elevarte de un nivel de consciencia a otro es la única ascensión que experimentarás jamás. Ninguna persona puede elevarte al nivel que deseas. El poder de ascender está dentro de ti; es tu consciencia. Te apropias de la consciencia del nivel que deseas expresar al declarar que ahora estás expresando ese nivel. Eso es la ascensión. Es ilimitada, porque jamás agotarás tu capacidad de ascender. Dale la espalda a la superstición humana de la ascensión, con su creencia en los maestros, y encuentra al maestro único y eterno que está dentro de ti.
“El que está en ti es mucho más grande que el que está en el mundo.” Cree en esto. No continúes en la ceguera, siguiendo el espejismo de los maestros. Te aseguro que esa búsqueda sólo puede acabar en la decepción.
“Si me niegas (tu consciencia de ser), yo también te negaré a ti.” “No tendrás a ningún otro Dios, excepto a MI.” “Quédate quieto y sabe que Yo SOY Dios.” “Ponedme a prueba, a ver si no os abro las ventanas del Cielo y derramo sobre vosotros una bendición, hasta que ya no haya sitio suficiente para recibirla.”
¿Crees que el Yo SOY es capaz de hacer eso? Entonces, declara que Yo SOY aquello que quieres ver derramándose. Afirma que eres aquello que deseas ser y que lo serás. No te lo daré por los maestros, sino que, puesto que tú has reconocido que Yo SOY (tú) eso, te lo daré, porque Yo SOY todas las cosas para todos.
Jesús no se permitía ser llamado el Buen Maestro. Él sabía que sólo hay un buen maestro. Sabía que ése es Su Padre en el Cielo: la consciencia de ser. “El Reino de Dios” (el Bien) y el Reino de los Cielos están dentro de ti.
Tu creencia en los maestros es una confesión de tu esclavitud. Sólo los esclavos tienen amos. Cambia tu concepto de ti mismo y, sin la ayuda de maestros ni de ninguna otra persona, transformarás automáticamente tu mundo para que se adapte a tu nueva idea de ti mismo.
En el Libro de los Números se dice que hubo una época en la que los seres humanos se consideraban a sí mismos como saltamontes y, debido a esa idea de sí mismos, vieron gigantes en las tierras. Esto se aplica a las personas de la actualidad como se aplicaba en el día en que fue escrito. El concepto que tiene una persona de sí misma es tan similar al caso de los saltamontes que automáticamente hace que las situaciones que le rodean parezcan gigantescas; en su ceguera, pide a gritos a los maestros que le ayuden a luchar contra sus gigantescos problemas.
Jesús intentó mostrarle a la gente que la salvación estaba en su interior y le advirtió que no buscara a un salvador en los lugares o las personas. Si alguien viene y te dice, “busca aquí o busca ahí”, no le creas, porque el Reino de los Cielos está dentro de ti.
Jesús no sólo no permitió que le llamaran el Buen Maestro, sino que advirtió a sus seguidores: “No saludéis a nadie por el camino”. Dejó claro que no deberían reconocer a ninguna autoridad o persona superior que no fuera Dios, el Padre.
Jesús estableció la identidad del Padre como la consciencia de ser de la persona. “Mi Padre y yo somos uno, pero mi Padre es más grande que yo.” Yo SOY uno con todo aquello que soy consciente de ser. Yo SOY más grande que aquello que soy consciente de ser. El creador es siempre más grande que su creación.
“Como Moisés levantó la serpiente en el desierto, así tiene que ser levantado el Hijo del Hombre.” La serpiente simboliza la idea actual que la persona tiene de sí misma, de ser como una lombriz en la tierra, viviendo en el desierto de la confusión humana. Del mismo modo que Moisés se levantó de su idea de sí mismo de “lombriz de la tierra” para descubrir que Dios era su consciencia de ser, “El Yo SOY me ha enviado”, también debes levantarte tú. El día que declares, como lo hizo Moisés, “Yo SOY el que Yo SOY”, ese día tu declaración florecerá en el desierto.
Tu consciencia es el mago maestro que hace aparecer todas las cosas cuando se convierte en aquello que quiere hacer aparecer. Este Señor y Maestro que tú eres puede hacer que aparezca en tu mundo todo aquello que tú eres consciente de ser, y lo hace.
“Ninguna persona (manifestación) viene a mí si no es atraída por mi Padre, y mi Padre y yo somos uno.” Tú estás continuamente atrayendo hacia ti aquello que eres consciente de ser. Cambia tu idea de ti mismo: haz que deje de ser la de un esclavo para convertirse en la idea de Cristo. No debes avergonzarte de afirmar esto; solamente cuando afirmes “Yo SOY Cristo” podrás hacer todas las obras de Cristo.
“Las obras que yo hago, vosotros también las haréis, y más grandes que éstas las haréis, porque yo me voy al Padre.” “Él se hizo igual a Dios y no consideró ninguna usurpación realizar las obras de Dios.” Jesús sabía que cualquier persona que se atreviera a declarar que es Cristo tendría automáticamente la capacidad de expresar las obras de su idea de Cristo. Jesús sabía también que el uso exclusivo de este principio de expresión no le había sido dado sólo a Él. Se refería constantemente a Su Padre en el Cielo. Afirmaba que Sus obras no sólo serían equivalentes, sino que serían superadas por la persona que se atreviera a concebir que era más grande que El (Jesús), que la idea que Él tenía de Sí Mismo.
Al afirmar que Él y Su Padre eran uno, pero que Su Padre era más grande que Él, Jesús revelaba que su consciencia (Padre) era una con aquello que Él era consciente de ser. Descubrió que, como Padre o consciencia, Él era más grande que aquello que Él, como Jesús, era consciente de ser. Tú y tu idea de ti mismo sois uno. Tú eres y siempre serás más grande que cualquier idea que puedas llegar a tener de ti mismo. El hombre no consigue hacer las obras de Jesucristo porque intenta realizarlas desde su nivel de consciencia actual. Jamás trascenderás tus logros actuales a través del sacrificio y el esfuerzo. Tu actual nivel de consciencia sólo será trascendido cuando dejes el estado actual y te eleves a un nivel superior.
Te elevas a un nivel de consciencia superior alejando tu atención de tus limitaciones actuales y colocándola en aquello que deseas ser. No intentes esto soñando despierto o haciéndote ilusiones, sino de una forma positiva. Afirma que eres la cosa deseada. Yo SOY eso; nada de sacrificios, nada de dietas, nada de trucos humanos. Lo único que se te pide es que aceptes tu deseo. Si te atreves a declararlo, lo expresarás.
Medita sobre esto. “No me regocijo en los sacrificios de los hombres. Ni con la fuerza ni con el poder, sino con mi espíritu. Pedid y recibiréis. Venid a comer y beber sin precio.”
Las obras están acabadas. Lo único que necesitas hacer para dejar que estas cualidades se expresen es afirmar: Yo SOY eso. Declara que eres aquello que deseas ser y lo serás. Las expresiones siguen a las impresiones; no las preceden. La prueba de que lo eres seguirá a la afirmación de que lo eres, no la precederá.
“Dejadlo todo y seguidme” es una invitación doble para ti. Primero te invita a alejarte completamente de todos los problemas y, luego, te insta a que sigas caminando en la afirmación de que tú eres aquello que deseas ser. No seas como la esposa de Lot, que mira atrás y se convierte en una estatua de sal o es conservada en el pasado que está muerto. Debes ser como un Lot que no mira atrás, sino que mantiene la vista enfocada en la tierra prometida, en la cosa deseada.
Haz esto y sabrás que has encontrado al maestro, al Mago Maestro, que hace que lo invisible se vuelva visible mediante la orden de “Yo SOY ESO”.
`
            },
                                {
                nombre: "Capítulo 2",
                texto: `Texto del capítulo 2...`
            },
                                {
                nombre: "Capítulo 2",
                texto: `Texto del capítulo 2...`
            }
        ]
    }
