        const sentireselsecreto = {
        id: "sentireselsecreto",
        titulo: "Sentir es el Secreto",
        autor: "Neville Goddard",

        capitulos: [

            {
                nombre: "Capítulo 1",
                texto: `La Ley y Su Operación
 
EL MUNDO, y todo dentro de él, es la conciencia del hombre condicionada y objetivada. La conciencia es la causa así como la sustancia del mundo entero. Entonces es a la conciencia a quien debemos dirigirnos si queremos descubrir el secreto de la creación.
 
El conocimiento de la ley de la conciencia y el método de operar esta ley te permitirá lograr todo lo que desees en la vida. Armado con el conocimiento de como funciona esta ley, puedes construir y mantener un mundo ideal. La conciencia es la única y sola realidad, no figurativamente sino realmente. Para explicarlo más claro, esta realidad puede ser comparada con un flujo que se divide en dos partes, el consciente y el subconsciente. Para operar inteligentemente la ley de la conciencia es necesario entender la relación entre lo consciente y lo subconsciente. Lo consciente es personal y selectivo; lo subconsciente es impersonal y no selectivo. Lo consciente es el reino del efecto, lo subconsciente es el reino de la causa. Estos dos aspectos son las divisiones masculina y femenina de la conciencia. El consciente es masculino; el subconsciente es femenino. El consciente genera ideas e imprime estas ideas en el subconsciente; el subconsciente recibe ideas y les da forma y expresión. Por esta ley – primero concibiendo una idea y luego imprimiendo la idea concebida en el subconsciente – todas las cosas evolucionan de la conciencia; y sin esta secuencia no hay nada hecho que sea hecho. El consciente imprime en el subconsciente mientras el subconsciente expresa todo lo que se le imprime. El subconsciente no origina ideas pero acepta como verdaderas aquellas que la mente consciente siente como verdaderas y de una manera que sólo el subconsciente conoce éste objetiva las ideas aceptadas. Por lo tanto, a través de su poder para imaginar y sentir y su libertad para elegir la idea que abrigará, el hombre tiene control sobre su creación. El control del subconsciente se logra a través del control de tus ideas y sentimientos.
 
El mecanismo de creación está escondido en la misma profundidad del subconsciente, el aspecto femenino o la matriz de la creación. El subconsciente trasciende la razón y es independiente de la inducción. Contempla un sentimiento como un hecho existiendo dentro de sí mismo y al asumir esto procede para darle expresión. El proceso creativo comienza con una idea y su ciclo corre su curso como sentimiento y termina en una voluntad de actuar. Las ideas son impresas en el subconsciente a través del medio del sentimiento. Ninguna idea puede ser impresa en el subconsciente hasta que es sentida, pero una vez que es sentida – sea buena, mala o indiferente – debe ser expresada. Sentir es la única y sola manera a través de la cual las ideas son expresadas al subconsciente. Por lo tanto, el hombre que no controla sus sentimientos puede imprimir fácilmente al subconsciente con estados indeseados. Por controlar los sentimientos no quiero decir reprimir o suprimir los sentimientos, sino más bien disciplinarse a uno mismo para imaginar y abrigar sólo tales sentimientos que contribuyan a su felicidad. El control de los sentimientos es muy importante para una vida plena y feliz. Nunca abrigues un sentimiento indeseado ni apoyes ningún perjuicio de ninguna forma. No te concentres en tus imperfecciones o en las de los demás. De otra manera estarás imprimiendo al subconsciente con estas limitaciones. Lo que no quieres que te hagan, no sientas que te lo hacen a ti o a otro. Esta es la ley completa de (para) una vida plena y feliz. Todo lo demás es palabrería.
 
Cada sentimiento hace una impresión subconsciente que debe ser expresada, a menos que sea contrarrestada por un sentimiento más poderoso de una naturaleza opuesta. El que domina de dos sentimientos es el que se expresa. Soy sano es un sentimiento más fuerte que seré sano. Sentir que seré es confesar que no lo soy; Yo soy es más fuerte que no lo soy. Lo que sientes que eres siempre domina lo que sientes que te gustaría ser; por lo tanto, para que el deseo se realice debe sentirse como un estado donde ya es [una realidad], en lugar de un estado donde no lo es. La sensación precede a la manifestación y es la fundación sobre la cual toda manifestación descansa. Se cuidadoso de tus estados de ánimo y sentimientos, porque hay una conexión irrompible entre tus sentimientos y tu mundo visible. Tu cuerpo es un filtro emocional y soporta las marcas inconfundibles de tus emociones predominantes. Los disturbios emocionales, especialmente las emociones suprimidas, son las causas de toda enfermedad. El sentimiento intenso con respecto a algún perjuicio sin verbalizarse o expresarse, es el comienzo de las enfermedades tanto en el cuerpo como en el ambiente. No abrigues el sentimiento de arrepentimiento o fracaso porque la frustración o desapego de tu objetivo resulta en enfermedad.
 
Piensa sintiendo solo en el estado que deseas realizar. Sentir la realidad del estado buscado y vivir y actuar desde esa convicción es la manera de todos los aparentes milagros. Todos los cambios de expresión se traen a través del cambio de sentimiento. Un cambio de sentimiento es un cambio de destino. Toda creación ocurre en el dominio del subconsciente. Lo que debes adquirir, entonces, es un control reflexivo del funcionamiento del subconsciente, es decir, el control de tus ideas y sentimientos. El azar o accidente no es responsable por las cosas que te ocurren, ni el destino predestinado es el autor de tu fortuna o tu desgracia. Las impresiones de tu subconsciente determinan las condiciones de tu mundo. El subconsciente no es selectivo; es impersonal y no respeta a las personas. El subconsciente no se preocupa por la verdad o falsedad de tu sentimiento. Siempre acepta como cierto aquello que tú sientes como verdadero. El sentimiento es el consentimiento del subconsciente respecto a la verdad de aquello que es declarado verdadero. Por esta cualidad del subconsciente no hay nada imposible para el hombre. Lo que sea que la mente de un hombre pueda concebir y sentir como verdadero, el subconsciente puede y debe objetivar. Tus sentimientos crean el patrón desde el cual tu mundo es creado y un cambio de sentimiento es un cambio de patrón.
 
El subconsciente nunca falla en expresar aquello que se le imprime. En el momento en que recibe una impresión comienza a elaborar las formas de su expresión. Acepta el sentimiento impreso en él, tu sentimiento, como un hecho existiendo dentro de sí mismo e inmediatamente comienza a producir en el mundo exterior u objetivo lo que se asemeja exactamente a ese sentimiento. El subconsciente nunca modifica las creencias que el hombre acepta. Las expresa hasta en su último detalle ya sean beneficiosas o no.
 
Para imprimir el subconsciente con el estado deseable debes asumir el sentimiento que sería tuyo si ya hubieras realizado tu deseo. Al definir tu objetivo debes concernirte sólo con el objetivo mismo. La forma de expresión o las dificultades involucradas no deben ser consideradas por ti. Lo que se piensa con sentimiento en cualquier estado se imprime en el subconsciente. Por lo tanto, si te concentras más que nada en las dificultades, barreras o retrasos, el subconsciente, por su naturaleza no selectiva, acepta el sentimiento de dificultades y obstáculos como tu petición y procede a producirlos en tu mundo exterior. 
 
El subconsciente es la matriz de la creación. Recibe la idea en sí mismo a través de los sentimientos del hombre. Nunca cambia la idea que recibe, pero siempre le da forma. Por lo tanto, el subconsciente expresa la idea a imagen y semejanza del sentimiento que recibe. Sentir un estado de desesperanza o imposibilidad es imprimir al subconsciente con la idea de fallar. Aunque el subconsciente le sirve al hombre fielmente no se debe deducir que la relación es la de un sirviente a su maestro como se concebía antiguamente. Los profetas antiguos lo llaman el esclavo y sirviente del hombre. San Pablo lo personificó como una “mujer” y dijo: “La mujer debe estar sujeta al hombre en todo”. El subconsciente sirve al hombre y fielmente le da forma a sus sentimientos. Sin embargo, el subconsciente tiene un disgusto distintivo por la compulsión y responde a la persuasión en lugar de al comando; consecuentemente, se parece a la esposa amorosa más que al sirviente.
 
“El esposo dirige a la esposa”. (Eph. 5), puede no ser cierto del hombre y la mujer en su relación terrestre pero es cierto del consciente y el subconsciente, o de los aspectos masculino y femenino de la conciencia. El misterio al cual Pablo se refería cuando escribió, “Este es un gran misterio... Aquel que ama a su esposa se ama a sí mismo... Y ellos dos han de ser uno en la carne”. Es simplemente el misterio de la conciencia. La conciencia es realmente una e indivisa pero por el bien de la creación parece estar dividida en dos.
 
El consciente (objetivo) o aspecto masculino verdaderamente es la cabeza y domina al subconsciente (subjetivo) o aspecto femenino. Sin embargo, este liderazgo no es ese del tirano sino del amante. Entonces al asumir el sentimiento que sería tuyo si ya estuvieras en posesión de tu objetivo, el subconsciente se motiva para construir lo que se asemeje exactamente a tu asunción. Tus deseos no son aceptados subconscientemente hasta que asumes el sentimiento de su realidad, porque sólo a través del sentimiento es una idea aceptada subconscientemente y sólo a través de esta aceptación subconsciente puede ser expresada alguna vez.
 
Es más fácil atribuirle tu sentimiento a eventos en el mundo que admitir que las condiciones del mundo reflejan tu sentimiento. Sin embargo, es eternamente cierto que el exterior refleja lo interior. “Como es adentro es afuera”. “Un hombre no puede recibir nada a menos que le sea dado desde el cielo”. Y “El reino de los cielos está dentro de ti”. Nada viene de afuera; todas las cosas vienen de adentro – del subconsciente. Es imposible para ti ver otra cosa que los contenidos de tu conciencia. Tu mundo en cada detalle es la conciencia objetivada. Los estados objetivos son testigos de las impresiones del subconsciente. Un cambio de impresión resulta en un cambio de expresión.
 
El subconsciente acepta como verdadero aquello que tú sientes como verdadero y debido a que la creación es el resultado de las impresiones del subconsciente, tú, por medio de tus sentimientos, determinas la creación. Ya eres aquello que deseas ser, y tu negativa a creer esto es la única razón por la que no lo ves. Buscar en el exterior por aquello que no sientes que eres es buscar en vano, porque nunca encontramos aquello que deseamos; encontramos sólo aquello que somos. Resumiendo, expresas y tienes sólo aquello de lo que eres consciente de ser o poseer. “Al que tiene se le da”. Negar la evidencia de los sentidos y apropiarse del sentimiento del deseo cumplido es la manera para la realización de tu deseo.
 
La maestría del dominio de ti mismo sobre tus pensamientos y sentimientos – es el mayor logro. Sin embargo, hasta que este dominio de ti mismo se alcance a la perfección, de modo que en lugar de apariencia sientas todo lo que deseas sentir, usa el sueño y la oración para ayudarte en realizar tus estados deseados. Estas son dos puertas de enlace hacia el subconsciente.
`
            },
            {
                nombre: "Capítulo 2",
                texto: "Texto del capítulo 2..."
            }
        ]
    }
