        const sentireselsecreto = {
        id: "sentireselsecreto",
        titulo: "Sentir es el Secreto",
        autor: "Neville Goddard",

        capitulos: [

            {
                nombre: "Cap-1 La Ley y Su Operación",
                texto: `El mundo, y todo dentro de él, es la conciencia del hombre condicionada y objetivada. La conciencia es la causa así como la sustancia del mundo entero. Entonces es a la conciencia a quien debemos dirigirnos si queremos descubrir el secreto de la creación.
El conocimiento de la ley de la conciencia y el método de operar esta ley te permitirá lograr todo lo que desees en la vida. Armado con el conocimiento de como funciona esta ley, puedes construir y mantener un mundo ideal. La conciencia es la única y sola realidad, no figurativamente sino realmente. Para explicarlo más claro, esta realidad puede ser comparada con un flujo que se divide en dos partes, el consciente y el subconsciente. Para operar inteligentemente la ley de la conciencia es necesario entender la relación entre lo consciente y lo subconsciente. Lo consciente es personal y selectivo; lo subconsciente es impersonal y no selectivo. Lo consciente es el reino del efecto, lo subconsciente es el reino de la causa. Estos dos aspectos son las divisiones masculina y femenina de la conciencia. El consciente es masculino; el subconsciente es femenino. El consciente genera ideas e imprime estas ideas en el subconsciente; el subconsciente recibe ideas y les da forma y expresión. Por esta ley – primero concibiendo una idea y luego imprimiendo la idea concebida en el subconsciente – todas las cosas evolucionan de la conciencia; y sin esta secuencia no hay nada hecho que sea hecho. El consciente imprime en el subconsciente mientras el subconsciente expresa todo lo que se le imprime. El subconsciente no origina ideas pero acepta como verdaderas aquellas que la mente consciente siente como verdaderas y de una manera que sólo el subconsciente conoce éste objetiva las ideas aceptadas. Por lo tanto, a través de su poder para imaginar y sentir y su libertad para elegir la idea que abrigará, el hombre tiene control sobre su creación. El control del subconsciente se logra a través del control de tus ideas y sentimientos.
El mecanismo de creación está escondido en la misma profundidad del subconsciente, el aspecto femenino o la matriz de la creación. El subconsciente trasciende la razón y es independiente de la inducción. Contempla un sentimiento como un hecho existiendo dentro de sí mismo y al asumir esto procede para darle expresión. El proceso creativo comienza con una idea y su ciclo corre su curso como sentimiento y termina en una voluntad de actuar. Las ideas son impresas en el subconsciente a través del medio del sentimiento. Ninguna idea puede ser impresa en el subconsciente hasta que es sentida, pero una vez que es sentida – sea buena, mala o indiferente – debe ser expresada. Sentir es la única y sola manera a través de la cual las ideas son expresadas al subconsciente. Por lo tanto, el hombre que no controla sus sentimientos puede imprimir fácilmente al subconsciente con estados indeseados. Por controlar los sentimientos no quiero decir reprimir o suprimir los sentimientos, sino más bien disciplinarse a uno mismo para imaginar y abrigar sólo tales sentimientos que contribuyan a su felicidad. El control de los sentimientos es muy importante para una vida plena y feliz. Nunca abrigues un sentimiento indeseado ni apoyes ningún perjuicio de ninguna forma. No te concentres en tus imperfecciones o en las de los demás. De otra manera estarás imprimiendo al subconsciente con estas limitaciones. Lo que no quieres que te hagan, no sientas que te lo hacen a ti o a otro. Esta es la ley completa de (para) una vida plena y feliz. Todo lo demás es palabrería.
Cada sentimiento hace una impresión subconsciente que debe ser expresada, a menos que sea contrarrestada por un sentimiento más poderoso de una naturaleza opuesta. El que domina de dos sentimientos es el que se expresa. Soy sano es un sentimiento más fuerte que seré sano. Sentir que seré es confesar que no lo soy; Yo soy es más fuerte que no lo soy. Lo que sientes que eres siempre domina lo que sientes que te gustaría ser; por lo tanto, para que el deseo se realice debe sentirse como un estado donde ya es [una realidad], en lugar de un estado donde no lo es. La sensación precede a la manifestación y es la fundación sobre la cual toda manifestación descansa. Se cuidadoso de tus estados de ánimo y sentimientos, porque hay una conexión irrompible entre tus sentimientos y tu mundo visible. Tu cuerpo es un filtro emocional y soporta las marcas inconfundibles de tus emociones predominantes. Los disturbios emocionales, especialmente las emociones suprimidas, son las causas de toda enfermedad. El sentimiento intenso con respecto a algún perjuicio sin verbalizarse o expresarse, es el comienzo de las enfermedades tanto en el cuerpo como en el ambiente. No abrigues el sentimiento de arrepentimiento o fracaso porque la frustración o desapego de tu objetivo resulta en enfermedad.
Piensa sintiendo solo en el estado que deseas realizar. Sentir la realidad del estado buscado y vivir y actuar desde esa convicción es la manera de todos los aparentes milagros. Todos los cambios de expresión se traen a través del cambio de sentimiento. Un cambio de sentimiento es un cambio de destino. Toda creación ocurre en el dominio del subconsciente. Lo que debes adquirir, entonces, es un control reflexivo del funcionamiento del subconsciente, es decir, el control de tus ideas y sentimientos. El azar o accidente no es responsable por las cosas que te ocurren, ni el destino predestinado es el autor de tu fortuna o tu desgracia. Las impresiones de tu subconsciente determinan las condiciones de tu mundo. El subconsciente no es selectivo; es impersonal y no respeta a las personas. El subconsciente no se preocupa por la verdad o falsedad de tu sentimiento. Siempre acepta como cierto aquello que tú sientes como verdadero. El sentimiento es el consentimiento del subconsciente respecto a la verdad de aquello que es declarado verdadero. Por esta cualidad del subconsciente no hay nada imposible para el hombre. Lo que sea que la mente de un hombre pueda concebir y sentir como verdadero, el subconsciente puede y debe objetivar. Tus sentimientos crean el patrón desde el cual tu mundo es creado y un cambio de sentimiento es un cambio de patrón.
El subconsciente nunca falla en expresar aquello que se le imprime. En el momento en que recibe una impresión comienza a elaborar las formas de su expresión. Acepta el sentimiento impreso en él, tu sentimiento, como un hecho existiendo dentro de sí mismo e inmediatamente comienza a producir en el mundo exterior u objetivo lo que se asemeja exactamente a ese sentimiento. El subconsciente nunca modifica las creencias que el hombre acepta. Las expresa hasta en su último detalle ya sean beneficiosas o no.
Para imprimir el subconsciente con el estado deseable debes asumir el sentimiento que sería tuyo si ya hubieras realizado tu deseo. Al definir tu objetivo debes concernirte sólo con el objetivo mismo. La forma de expresión o las dificultades involucradas no deben ser consideradas por ti. Lo que se piensa con sentimiento en cualquier estado se imprime en el subconsciente. Por lo tanto, si te concentras más que nada en las dificultades, barreras o retrasos, el subconsciente, por su naturaleza no selectiva, acepta el sentimiento de dificultades y obstáculos como tu petición y procede a producirlos en tu mundo exterior. 
El subconsciente es la matriz de la creación. Recibe la idea en sí mismo a través de los sentimientos del hombre. Nunca cambia la idea que recibe, pero siempre le da forma. Por lo tanto, el subconsciente expresa la idea a imagen y semejanza del sentimiento que recibe. Sentir un estado de desesperanza o imposibilidad es imprimir al subconsciente con la idea de fallar. Aunque el subconsciente le sirve al hombre fielmente no se debe deducir que la relación es la de un sirviente a su maestro como se concebía antiguamente. Los profetas antiguos lo llaman el esclavo y sirviente del hombre. San Pablo lo personificó como una “mujer” y dijo: “La mujer debe estar sujeta al hombre en todo”. El subconsciente sirve al hombre y fielmente le da forma a sus sentimientos. Sin embargo, el subconsciente tiene un disgusto distintivo por la compulsión y responde a la persuasión en lugar de al comando; consecuentemente, se parece a la esposa amorosa más que al sirviente.
“El esposo dirige a la esposa”. (Eph. 5), puede no ser cierto del hombre y la mujer en su relación terrestre pero es cierto del consciente y el subconsciente, o de los aspectos masculino y femenino de la conciencia. El misterio al cual Pablo se refería cuando escribió, “Este es un gran misterio... Aquel que ama a su esposa se ama a sí mismo... Y ellos dos han de ser uno en la carne”. Es simplemente el misterio de la conciencia. La conciencia es realmente una e indivisa pero por el bien de la creación parece estar dividida en dos.
El consciente (objetivo) o aspecto masculino verdaderamente es la cabeza y domina al subconsciente (subjetivo) o aspecto femenino. Sin embargo, este liderazgo no es ese del tirano sino del amante. Entonces al asumir el sentimiento que sería tuyo si ya estuvieras en posesión de tu objetivo, el subconsciente se motiva para construir lo que se asemeje exactamente a tu asunción. Tus deseos no son aceptados subconscientemente hasta que asumes el sentimiento de su realidad, porque sólo a través del sentimiento es una idea aceptada subconscientemente y sólo a través de esta aceptación subconsciente puede ser expresada alguna vez.
Es más fácil atribuirle tu sentimiento a eventos en el mundo que admitir que las condiciones del mundo reflejan tu sentimiento. Sin embargo, es eternamente cierto que el exterior refleja lo interior. “Como es adentro es afuera”. “Un hombre no puede recibir nada a menos que le sea dado desde el cielo”. Y “El reino de los cielos está dentro de ti”. Nada viene de afuera; todas las cosas vienen de adentro – del subconsciente. Es imposible para ti ver otra cosa que los contenidos de tu conciencia. Tu mundo en cada detalle es la conciencia objetivada. Los estados objetivos son testigos de las impresiones del subconsciente. Un cambio de impresión resulta en un cambio de expresión.
El subconsciente acepta como verdadero aquello que tú sientes como verdadero y debido a que la creación es el resultado de las impresiones del subconsciente, tú, por medio de tus sentimientos, determinas la creación. Ya eres aquello que deseas ser, y tu negativa a creer esto es la única razón por la que no lo ves. Buscar en el exterior por aquello que no sientes que eres es buscar en vano, porque nunca encontramos aquello que deseamos; encontramos sólo aquello que somos. Resumiendo, expresas y tienes sólo aquello de lo que eres consciente de ser o poseer. “Al que tiene se le da”. Negar la evidencia de los sentidos y apropiarse del sentimiento del deseo cumplido es la manera para la realización de tu deseo.
La maestría del dominio de ti mismo sobre tus pensamientos y sentimientos – es el mayor logro. Sin embargo, hasta que este dominio de ti mismo se alcance a la perfección, de modo que en lugar de apariencia sientas todo lo que deseas sentir, usa el sueño y la oración para ayudarte en realizar tus estados deseados. Estas son dos puertas de enlace hacia el subconsciente.
`
            },
            {
                nombre: "Cap-2 El Sueño",
                texto: `El Sueño, la vida que ocupa un tercio de nuestra estancia en la tierra, es la puerta natural hacia el subconsciente. Por eso nos ocupamos del sueño ahora. Los dos tercios conscientes de nuestra vida en la tierra son medidos por el grado de atención que le damos al sueño. Nuestra comprensión de y deleite en lo que el sueño tiene para conceder nos causará, noche tras noche, ponernos en camino a él como si estuviéramos yendo a una cita con un amante.
“En un sueño, en una visión de la noche, cuando el sueño profundo cae sobre los hombres, al dormir en la cama; entonces él abre los oídos de los hombres y les da sus instrucciones”. (Job 33). Es en el sueño y en la oración, un estado similar al sueño, que el hombre entra al subconsciente para hacer sus impresiones y recibir sus instrucciones. En estos estados el consciente y el subconsciente se unen creativamente. El aspecto masculino y el aspecto femenino se vuelven uno. El sueño es el momento cuando el aspecto masculino o mente consciente va del mundo de los sentidos a buscar a su amante o parte subconsciente. El subconsciente – a diferencia de la mujer del mundo que se casa con su marido para cambiarlo – no tiene deseo de cambiar al estado consciente o de vigilia, sino que lo ama como es y reproduce fielmente su semejanza en el mundo exterior de la forma. Las condiciones y eventos de tu vida son tus niños formados de los moldes de las impresiones de tu subconsciente en el sueño. Son hechos en imagen y semejanza de tu sentimiento más interno que ellos pueden revelarte a ti a ti mismo.
“Como es en el cielo así es en la tierra”. Como es en el subconsciente así es en la tierra. Lo que sea que tengas en la conciencia cuando vas a dormir es la medida de tu expresión en los dos tercios conscientes de tu vida en la tierra. Nada te impide realizar tu objetivo salvo tu incapacidad de sentir que ya eres aquello que deseas ser, o que ya estás en posesión de la cosa que buscas. Tu subconsciente le da forma a tus deseos sólo cuando sientes tu deseo realizado. El estado inconsciente del sueño es el estado normal del subconsciente. Debido a que todas las cosas vienen desde tu interior, y tu concepción de ti mismo determina aquello que viene, deberías siempre sentir el deseo como ya realizado antes de irte a dormir. Nunca traes de lo profundo de ti mismo aquello que deseas; siempre traes aquello que eres, y eres aquello que sientes que eres así como aquello que sientes cierto de los demás.
Para ser realizado, entonces, el deseo debe ser resuelto en el sentimiento de ser o tener o presenciar el estado buscado. Esto se logra al asumir el sentimiento del deseo realizado. El sentimiento que viene en respuesta a la pregunta “¿Cómo me sentiría si mi deseo se cumpliera?” es el sentimiento que debería monopolizar e inmovilizar tu atención mientras te relajas para dormir. Debes estar en la conciencia de ser o tener aquello que deseas ser o tener antes de dormirte.
Una vez dormido el hombre no tiene libertad de elección. Su sueño es completamente dominado por su último concepto despierto de su ser. Por lo tanto, él debería siempre asumir el sentimiento de logro y satisfacción antes de retirarse a dormir, “Ven ante mí con canto y agradecimiento”, “Entra en sus portones con gratitud y en sus tribunales con elogios”. Tu disposición de ánimo previa al sueño define tu estado de conciencia mientras entras en la presencia del amante eterno, el subconsciente. Tu mente subconsciente te ve exactamente como te sientes que eres. Si mientras te preparas para dormir asumes y mantienes la conciencia de éxito al sentir “Yo soy exitoso”, debes ser exitoso. Tiéndete sobre tu espalda con la cabeza en un nivel con tu cuerpo. Siente como serías si estuvieras en posesión de tu deseo y relájate tranquilamente hacia la inconsciencia.
“Aquel que mantenga Israel no deberá dormir”. Sin embargo, “Él le da a su amada el sueño”. El subconsciente nunca duerme. El sueño es la puerta por la cual la mente consciente o mente despierta entra para unirse creativamente con el subconsciente. El sueño oculta el acto creativo mientras el mundo objetivo lo revela. En el sueño el hombre imprime en el subconsciente su concepción de sí mismo.
La descripción más hermosa de este romance del consciente y el subconsciente es la que se cuenta en la “Canción de Salomón”. “Por la noche en mi cama busqué a aquel a quien mi alma ama... Encontré a quien mi alma ama; lo sostuve y nunca lo dejé ir, hasta que lo llevé a la casa de mi madre y a la recámara de ella que me concibió”. Preparándote para dormir, siéntete en el estado del deseo respondido y luego relájate en la inconsciencia. Tu deseo realizado es lo que buscas. Por la noche en tu cama buscas el sentimiento del deseo realizado de modo que lo puedas llevar a la recámara de ella que te concibió, al sueño o al subconsciente que te dio forma, para que este deseo también pueda expresarse. Esta es la manera para descubrir y conducir tus deseos al subconsciente. Siéntete en el estado del deseo realizado y tranquilamente déjate caer al sueño. Noche tras noche deberías asumir el sentimiento de ser, tener y ser testigo de aquello que buscas ser, poseer y ver manifestado. Nunca vayas a dormir sintiéndote desanimado o insatisfecho. Nunca duermas con la conciencia de la insuficiencia. Tu subconsciente, cuyo estado natural es el sueño, te ve como tú crees que eres, y ya sea que lo que crees es bueno, malo o indiferente, el subconsciente va a expresar fielmente tu creencia. Así como te sientes la imprimes a ella; y ella, la amante perfecta, le da forma a estas impresiones y las expresa como hijos de su amado. “Toda hermosa eres, mi amor, no hay mancha en ti”, es la actitud mental para adoptar antes de dormir.
Descarta las apariencias y siente las cosas como deseas que sean, porque “Él declara cosas que no se ven como si se vieran y lo que no se veía se vuelve visible”. Asumir el sentimiento de satisfacción es declarar aquellas condiciones que reflejan satisfacción como si fuesen una realidad actual. “Las señales siguen, no preceden”. La prueba de lo que eres seguirá a la conciencia que eres, no la precederá. Eres un soñador eterno soñando sueños no eternos. Tus sueños toman forma cuando asumes el sentimiento de su realidad. No te limites al pasado. Sabiendo que nada es imposible para la conciencia, comienza a imaginar estados más allá de las experiencias del pasado. Lo que sea que la mente del hombre puede imaginar lo puede realizar. Todos los estados objetivos (visibles) fueron primero estados subjetivos (invisibles) y los hiciste visibles al asumir el sentimiento de su realidad. El proceso creativo es primero imaginar y luego creer el estado imaginado. Siempre imagina y espera lo mejor.
El mundo no puede cambiar hasta que cambies tu concepción de él. “Como es adentro es afuera”. Las naciones así como la gente sólo son lo que tú crees que son. Sin importar cual sea el problema, sin importar donde está, sin importar a quien concierne, no tienes a nadie que cambiar excepto a ti mismo, y no tienes un oponente o un ayudante en realizar el cambio dentro de ti mismo. No tienes nada que hacer salvo convencerte de la realidad de lo que deseas ver manifestado. Tan pronto como logras convencerte de la realidad del estado que buscas, los resultados siguen para confirmar tu creencia fija. Nunca le sugieras a otro el estado que deseas verlo expresar; sino que convéncete de que él ya es lo que deseas que sea.
La realización de tu deseo se logra al asumir el sentimiento del deseo cumplido. No puedes fallar a menos que no te convenzas de la realidad de tu deseo. 
Un cambio de creencia se confirma por medio de un cambio de expresión. Cada noche cuando vas a dormir siéntete satisfecho y sin manchas [o claro], porque tu amante subjetiva siempre forma el mundo objetivo a imagen y semejanza de tu concepción de él, la concepción definida por tu sentimiento. Los dos tercios conscientes de tu vida en la tierra siempre corroboran o son testigos de tus impresiones subconscientes. Las acciones y eventos del día son efectos; no son causas. El libre albedrío es sólo la libertad de elección. “Elige este día a quien servirás” es tu libertad de elegir el tipo de disposición de ánimo que asumes; pero la expresión de esa disposición es el secreto del subconsciente. El subconsciente recibe impresiones sólo a través de los sentimientos del hombre y en una manera conocida sólo por el subconsciente éste le da forma y expresión a estas impresiones. Las acciones del hombre son determinadas por sus impresiones subconscientes. Su ilusión de libre albedrío, su creencia en la libertad de acción, es sólo ignorancia de las causas que lo hacen actuar. Él piensa que es libre porque ha olvidado el vínculo entre él y el evento.
El hombre despierto está bajo la compulsión de expresar sus impresiones subconscientes. Si en el pasado él imprimió algo en sí mismo de una manera poco sensata, entonces hay que dejarlo que comience a cambiar sus pensamientos y sentimientos, porque sólo cuando lo haga él cambiará su mundo. No pierdas ni un momento en lamentarte, porque pensar sintiendo los errores del pasado es reinfectarte. “Deja que los muertos entierren a los muertos”. Sal de las apariencias y asume el sentimiento que sería tuyo si ya fueras el (lo) que deseas ser. Sentir un estado produce ese estado. La parte que juegas en el escenario del mundo es determinada por tu concepción de ti mismo. Sintiendo tu deseo realizado y relajándote tranquilamente hacia el sueño, te pones como estrella protagonista para interpretar tu papel en la tierra mañana, y mientras duermes ensayas y eres instruido en tu papel. La aceptación del final [de la 'obra'] automáticamente da los medios de (para) su realización. Que eso quede claro. Si mientras te preparas para dormir, no te sientes conscientemente en el estado del deseo cumplido, entonces llevarás contigo a la recámara de aquella que te concibió, la suma total de las reacciones y sentimientos del día de vigilia; y mientras duermes serás instruido en una manera en la cual serán expresados mañana. Te levantarás creyendo que eres un agente libre, sin darte cuenta de que cada acción y evento del día de mañana estarán predeterminados por tu concepto del yo cuando te dormiste. Tu única libertad es entonces tu libertad de reacción. Eres libre de elegir como sentirte y reaccionar al drama del día, pero el drama – las acciones, eventos y circunstancias del día – ya ha sido determinado.
A menos que definas conscientemente y a propósito la actitud mental con la cual te vas a dormir, inconscientemente vas a dormir en la actitud mental compuesta por todos los sentimientos y reacciones del día. Cada reacción hace una impresión subconsciente y, a menos que sea contrarrestada por un sentimiento opuesto y más dominante, es la causa de acción futura. Las ideas envueltas en sentimiento son acciones creativas. Usa tu derecho divino sabiamente. A través de tu habilidad para pensar y sentir tienes el dominio de toda la creación. Mientras estás despierto eres un jardinero seleccionando semillas para tu jardín, pero “Excepto que un grano de trigo caiga en el suelo y muera, se mantiene solo; pero si muere, trae mucho fruto”. Tu concepción de ti mismo mientras te estás quedando dormido es la semilla que sueltas en el terreno del subconsciente. El quedarte dormido sintiéndote satisfecho y feliz hace que las condiciones y eventos aparezcan en tu mundo confirmando estas actitudes mentales. El sueño es la puerta hacia el cielo. Lo que incluyes como sentimiento lo proyectas como una condición, acción u objeto en el espacio. Por lo tanto, duerme en el sentimiento del deseo cumplido. “Como es en la conciencia es en la tierra”. 
`
            },
                {
                nombre: "Cap-3 La Oración",
                texto: `La Oración, tanto como el sueño, es también una entrada hacia el subconsciente, “Cuando ores, entra en tu aposento, y cuando hayas cerrado tu puerta, ora al Padre en secreto y tu Padre en secreto te recompensará abiertamente”. La oración es una ilusión de sueño que disminuye la impresión del mundo externo y pone a la mente más receptiva a la sugestión desde adentro. La mente durante la oración está en un estado de relajación y receptividad similar al sentimiento que se logra justo antes de que nos quedamos dormidos.
La oración no es tanto acerca de lo que pides, sino como te preparas para recibirlo. “Lo que sea que desees, cuando pides creyendo que lo has recibido, lo tendrás”. La única condición requerida es que creas que las oraciones ya se realizaron.
Tu oración debe ser respondida si asumes el sentimiento que sería tuyo si ya estuvieras en posesión de tu objetivo. En el momento en que aceptas el deseo como un hecho realizado el subconsciente encuentra los medios para su realización. Para orar exitosamente entonces, debes ceder al deseo, eso es, sentir el deseo realizado.
El hombre perfectamente disciplinado está siempre sintonizado con el deseo como un hecho cumplido. Él sabe que la conciencia es la única y sola realidad, que las ideas y sentimientos son hechos de la conciencia y son reales como objetos en el espacio; por lo tanto él nunca abriga un sentimiento que no contribuye a su felicidad porque los sentimientos son las causas de las acciones y circunstancias de su vida. Por otro lado, al hombre indisciplinado le resulta difícil creer aquello que los sentidos niegan y usualmente acepta o rechaza solamente basado en apariencias de los sentidos. Debido a esta tendencia a contar con la evidencia de los sentidos, es necesario ignorarlos antes de comenzar a orar, antes de intentar sentir aquello que ellos niegan. Cuando sea que estés en el estado mental, “Me gustaría pero no puedo”, más intentas y menos consigues obtener el deseo. Nunca atraes aquello que deseas pero siempre atraes aquello que estás consciente de ser.
La oración es el arte de asumir el sentimiento de ser y tener aquello que deseas. Cuando los sentidos confirman la ausencia del deseo, todos los esfuerzos conscientes de contrarrestar esta sugerencia son inútiles y tienden a intensificar la sugerencia. La oración es el arte de ceder al deseo y no de forzar al deseo. Cuando sea que tu sentimiento está en conflicto con tu deseo, sentir será lo que ganará. El sentimiento dominante invariablemente se expresa a sí mismo. La oración debe ser sin esfuerzo. Cuando se intenta fijar una actitud mental que los sentidos niegan, el esfuerzo es fatal.
Para ceder exitosamente al deseo como un hecho cumplido, debes crear un estado pasivo, una especie de ensueño o reflexión meditativa similar al sentimiento que precede al sueño. En tal estado relajado la mente se aleja del mundo objetivo y fácilmente siente la realidad del estado subjetivo. Es un estado en el cual eres consciente y bastante capaz de moverte o abrir tus ojos pero no tienes deseo de hacerlo. Una manera sencilla de crear este estado pasivo es relajarte en una silla confortable o en una cama. Si es en una cama, acuéstate sobre tu espalda con la cabeza al mismo nivel de tu cuerpo, cierra los ojos e imagina que estás somnoliento. Siente – “tengo sueño, tengo mucho, mucho sueño...” y dentro de un corto tiempo después te envuelve un sentimiento de lejanía acompañado por una laxitud (relajación) general y una pérdida de todo deseo de moverte. Sientes un descanso placentero, cómodo y no te inclinas a alterar tu posición, aunque bajo otras circunstancias no estarías cómodo. Cuando este estado pasivo se alcanza, imagina que has realizado tu deseo – no como fue realizado – sino simplemente el deseo realizado.
Imagina en forma de imágenes lo que deseas lograr en la vida; entonces siéntete como que ya lo has logrado. Los pensamientos producen pequeños movimientos de habla los cuales se pueden oír en el estado pasivo de oración como pronunciamientos desde afuera. Sin embargo, este grado de pasividad no es esencial para la realización de tus oraciones. Todo lo que es necesario es crear un estado pasivo y sentir el deseo cumplido.
Todo lo que podrías necesitar o desear ya es tuyo. No necesitas un ayudante que te lo de. Declara tus deseos una realidad imaginándolos y sintiéndolos como ya cumplidos. Cuando el final se acepta, te vuelves totalmente indiferente respecto al posible fracaso, porque la aceptación del final consigue los medios para ese final. Cuando emerges desde el momento de la oración es como que te mostraran el final feliz y exitoso de una obra aunque no te mostraran cómo se logró aquel final. Sin embargo, habiendo presenciado el final, sin importar cualquier secuencia anticlímax permaneces tranquilo y seguro en el conocimiento de que el final se ha definido perfectamente.
`
            },
                                {
                nombre: "Cap-4 Espíritu-Sentimiento",
                texto: `“NO por voluntad, ni por poder, sino por mi espíritu, dijo el Señor de las huestes”. Entra en el espíritu del estado que deseas asumiendo el sentimiento que sería tuyo si ya fueras quien quieres ser. Al captar el sentimiento del estado que buscas, te alivias de todo esfuerzo de hacerlo que sea una realidad, puesto que ya lo es. Hay un sentimiento definido asociado con cada idea en la mente del hombre. Capta el sentimiento asociado con tu deseo realizado asumiendo el sentimiento que sería tuyo si ya estuvieras en posesión de la cosa que deseas, y tu deseo se objetivará.
La fe es sentimiento, “De acuerdo a tu fe (sentimiento) será hacia ti”. Nunca atraes aquello que deseas pero siempre atraes aquello que eres. Como es un hombre, así ve. “A aquel que tiene le será dado y a aquel que no tiene se le quitará...”. Aquello que sientes tú mismo que eres, eres, y se te da aquello que eres. Entonces asume el sentimiento que sería tuyo si ya estuvieras en posesión de tu deseo, y tu deseo deberá realizarse. “Entonces Dios creó al hombre a su imagen, a imagen de Dios lo creó”. “Permite que esta mente sea en ti así como también fue en Jesucristo, quien asumiendo la forma de Dios no pensó que ser igual a Dios era un robo”. Eres aquello que crees que eres. En lugar de creer en Dios o en Jesús – cree que eres Dios o que eres Jesús. “Aquel que cree en mí, las obras que yo hago él también las hará” debería ser “Aquel que cree como yo creo, las obras que yo hago él también las hará”. Jesús no encontró extraño hacer las obras de Dios porque él creía que era Dios. “Yo y mi Padre somos uno”. Es natural hacer las obras de aquel que crees ser tú mismo. Entonces vive en el sentimiento de ser el (lo) que deseas ser y lo serás. Cuando un hombre cree en el valor del consejo que se le da y lo aplica, establece dentro de él la realidad del éxito.
`
            },
                                                {
                nombre: "Notas de un estudiante de Neville",
                texto: `Cuando pongas en práctica estas enseñanzas de Neville, debes visualizar y sentir tu deseo como ya cumplido ahora, dándole a tus escenas mentales el mayor grado de realismo posible y debes mantenerte haciendo esto hasta que te llegues a emocionar. Es muy importante llegar al punto en que surge la emoción porque es así como se causan las impresiones en la mente subconsciente. Hay que ser constantes y repetir el proceso hasta que lo que sea que deseemos se manifieste en el mundo físico. Recordemos que el cerebro es incapaz de diferenciar una experiencia física de una imaginaria, y las toma a ambas por verdaderas. Esto está demostrado hoy en día por la ciencia. Luego a nivel energético cualquier cosa que vivamos en nuestra imaginación sintiéndola como si fuera verdadera es en ese mismo momento una realidad.

NAMASTÉ
`
            }
        ]
    }
